'use client';

import { useState, useRef, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/context/AuthContext';
import { Button } from '@/components/ui/Button';
import { Loader2, ShieldCheck, ArrowRight } from 'lucide-react';
import { useToast } from '@/components/ui/Toaster';

export default function TwoFactorVerifyPage() {
  const [code, setCode] = useState(['', '', '', '', '', '']);
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  const { refreshUser } = useAuth();
  const { toast } = useToast();
  const inputRefs = useRef([]);

  useEffect(() => {
    inputRefs.current[0]?.focus();
  }, []);

  const handleChange = (index, value) => {
    if (!/^\d*$/.test(value)) return;

    const newCode = [...code];
    newCode[index] = value.slice(-1); // Only keep last typed digit
    setCode(newCode);

    // Auto-advance
    if (value && index < 5) {
      inputRefs.current[index + 1]?.focus();
    }
    
    // Auto-submit if full
    if (value && index === 5 && newCode.every(d => d !== '')) {
      handleVerify(newCode.join(''));
    }
  };

  const handleKeyDown = (index, e) => {
    if (e.key === 'Backspace' && !code[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const handleVerify = async (fullCode) => {
    const stringCode = typeof fullCode === 'string' ? fullCode : code.join('');
    if (stringCode.length < 6) return;

    setLoading(true);
    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token: stringCode, is2FA: true }),
      });
      const data = await res.json();
      
      if (res.ok) {
        await refreshUser();
        router.push('/');
      } else {
        toast({ title: data.error || 'Invalid code', variant: 'destructive' });
        setCode(['', '', '', '', '', '']);
        inputRefs.current[0]?.focus();
      }
    } catch {
      toast({ title: 'Verification failed', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center -mt-16 bg-background p-4 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0 bg-grid-pattern opacity-5 pointer-events-none" />
      <div className="absolute -top-32 -left-32 w-96 h-96 bg-primary/20 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute -bottom-32 -right-32 w-96 h-96 bg-blue-500/20 rounded-full blur-3xl pointer-events-none" />

      <div className="glass-card rounded-3xl p-8 sm:p-12 w-full max-w-md relative z-10 shadow-2xl flex flex-col items-center text-center">
        <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6">
          <ShieldCheck className="w-8 h-8 text-primary" />
        </div>
        
        <h1 className="text-2xl font-bold tracking-tight mb-2">Two-Factor Authentication</h1>
        <p className="text-muted-foreground text-sm mb-8">
          Enter the 6-digit verification code generated by your authenticator app.
        </p>

        <div className="flex justify-center gap-2 mb-8">
          {code.map((digit, i) => (
            <input
              key={i}
              ref={el => inputRefs.current[i] = el}
              type="text"
              inputMode="numeric"
              pattern="\d*"
              maxLength={1}
              value={digit}
              onChange={e => handleChange(i, e.target.value)}
              onKeyDown={e => handleKeyDown(i, e)}
              className="w-12 h-14 sm:w-14 sm:h-16 bg-secondary/80 border-2 border-transparent text-center text-xl sm:text-2xl font-bold rounded-xl focus:border-primary focus:bg-background outline-none transition-all"
            />
          ))}
        </div>

        <Button 
          className="w-full rounded-full h-12 text-base font-semibold"
          disabled={loading || code.some(d => d === '')}
          onClick={() => handleVerify()}
        >
          {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <><ArrowRight className="w-5 h-5 mr-2" /> Verify Code</>}
        </Button>

        <button 
          onClick={() => router.push('/login')} 
          className="mt-6 text-sm text-muted-foreground hover:text-foreground transition-colors font-medium"
        >
          Back to login
        </button>
      </div>
    </div>
  );
}
